name: "Test and Coverage report"
on:
  pull_request:
    branches:
      - release/dev

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
    with:
    package-manager: pnpm
    github-token: ${{ secrets.SECRET_TOKEN }}
