name: Coverage report
on:
  pull_request:
    branches:
      - release/dev
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          package-manager: pnpm
          github-token: ${{ secrets.PAT }}
          test-script: npm run test
